### ISSUE TITLE
Permission denied for bower-github.yml

### ISSUE THREAD

**Issue by fuzzdota** [Polymer/web-component-tester#168] opened 2015-05-13 23:04 UTC
Error is thrown when I try to install using npm with sudo.
```
sudo npm install -g web-component-tester
```
The error log:
```
Error: EACCES, permission denied '/home/localaccess/.config/configstore/bower-github.yml'
You don't have access to this file.

    at Object.fs.openSync (evalmachine.<anonymous>:432:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:286:15)
    at Object.create.all.get (/usr/lib/node_modules/web-component-tester/node_modules/bower/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/lib/node_modules/web-component-tester/node_modules/bower/node_modules/configstore/index.js:27:44)
    at readCachedConfig (/usr/lib/node_modules/web-component-tester/node_modules/bower/lib/config.js:22:23)
    at defaultConfig (/usr/lib/node_modules/web-component-tester/node_modules/bower/lib/config.js:11:24)
    at Object.<anonymous> (/usr/lib/node_modules/web-component-tester/node_modules/bower/lib/index.js:40:32)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
npm ERR! Linux 3.13.0-52-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "web-component-tester"
npm ERR! node v0.10.25
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! web-component-tester@3.1.3 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the web-component-tester@3.1.3 postinstall script 'node scripts/postinstall.js'.
npm ERR! This is most likely a problem with the web-component-tester package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls web-component-tester
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/localaccess/Desktop/Polymer/development/seed-element/npm-debug.log
```

I ran the following command line
```
sudo chown -R localaccess /home/localaccess/.config/configstore/
```
then check for permission. This is the result (notice, there is no bower-github.yml):
```
localaccess@administrator-Precision-T3610:~/Desktop/Polymer/development/seed-element$ ls -l /home/localaccess/.config/configstore
total 28
-rw------- 1 localaccess localaccess 37 May 13 15:50 insight-bower.yml
-rw-rw-r-- 1 localaccess localaccess 38 Feb 19 17:17 insight-yo.yml
-rw------- 1 localaccess localaccess 45 May 13 15:50 update-notifier-bower.yml
-rw------- 1 localaccess localaccess 45 Feb 19 17:17 update-notifier-generator-chromeapp.yml
-rw------- 1 localaccess localaccess 45 Feb 19 17:17 update-notifier-generator-mocha.yml
-rw------- 1 localaccess localaccess 45 Mar  2 11:29 update-notifier-web-component-tester.yml
-rw------- 1 localaccess localaccess 45 Feb 19 17:17 update-notifier-yo.yml
```

**Comment by rbjarnason** [comment] 2015-05-20 12:39
I have the same problem.

**Comment by rbjarnason** [comment] 2015-05-20 18:11
Actually, turned out those are permission problems root v. $user. I ended up installing wct locally.

**Comment by fuzzdota** [comment] 2015-05-21 00:07
@rbjarnason How did you install wct locally ? Sorry I'm not that of an expert on command line for Linux.

**Comment by touhonoob** [comment] 2015-05-31 10:49
Same issue on Debian Jessie

**Comment by ystreibel** [comment] 2015-06-01 11:48
:+1:

**Comment by timeu** [comment] 2015-06-01 12:08
@rbjarnason to install locally: `npm install web-component-tester`

And then just run `node_modules/web-component-tester/bin/wct`

**Comment by rookoolcedric** [comment] 2015-06-01 12:11
Same issue on Debian Stretch

**Comment by ystreibel** [comment] 2015-06-01 12:29
Like @timeu said to me, you can try to delete the /home/$USER/.npm folder and npm install web-component-tester.
It works for me !

**Comment by crhym3** [comment] 2015-06-08 10:20
Looks like it needs group rw permission:

```
chmod g+rw ~/.config/configstore/bower-github.yml
```

**Comment by torcellite** [comment] 2015-06-17 06:53
*bump*

Same problem on OS X Yosemite. I guess I'll have to install it locally and add an environment variable for now.

**Comment by gregoiremotot** [comment] 2015-06-19 11:41
Thanks crhym3 !

chmod g+rw ~/.config/configstore/bower-github.yml

fix problem for me.

**Comment by andreibotezatu** [comment] 2015-06-22 13:50
thanks crhym3

**Comment by JayHoltslander** [comment] 2015-08-04 21:55
Neither
``chmod g+rw ~/.config/configstore/bower-github.yml``
nor
``sudo chmod g+rw ~/.config/configstore/bower-github.yml``
resolved the issue for me.

**Comment by gazal-k** [comment] 2015-08-05 04:41
Same as @JayHoltslander. Giving group rw permissions didn't help.

**Comment by nhatbui** [comment] 2015-08-06 06:19
I had luck doing:
`sudo chown -R [username] ~/.cache/bower/`
`sudo chown -R [username] ~/.config/configstore/`

**Comment by gazal-k** [comment] 2015-08-06 12:11
Thanks @nhatbui. But still no luck :disappointed:

**Comment by JayHoltslander** [comment] 2015-08-06 20:25
@gazal-k Someone suggested to me that I'd messed up my home folder's permissions earlier and I'd have to repair them while booted off the recovery partition. I haven't done this yet myself to see if it solves my issue but you might want to look into it.

**Comment by kel-dev** [comment] 2015-08-10 07:58
@nhatbui sudo chown -R [username] ~/.config/configstore/ works for me. But I am not working with this 'Polymer/web-component-tester' package though...

**Comment by itrea** [comment] 2015-08-13 11:17
@nhatbui Thanks, this fixed my issue also

**Comment by Eugenitals** [comment] 2015-08-15 07:44
Thanks crhym3

**Comment by tomask-de** [comment] 2015-08-24 07:26
Hi,
the problem still occurs, when trying to install the package globally with `sudo npm install-g web-component-tester`. Changing the permissions as described above just fixes the issue for local (user-based) installation with `npm install web-component-tester`.

```sh
/usr/bin/wct-st -> /usr/lib/node_modules/web-component-tester/bin/wct-st

> web-component-tester@3.3.10 postinstall /usr/lib/node_modules/web-component-tester
> node scripts/postinstall.js


Error: EACCES, permission denied '/home/tkuchs/.config/configstore/bower-github.yml'
You don't have access to this file.

    at Object.fs.openSync (evalmachine.<anonymous>:439:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:290:15)
    at Object.create.all.get (/usr/lib/node_modules/web-component-tester/node_modules/bower/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/lib/node_modules/web-component-tester/node_modules/bower/node_modules/configstore/index.js:27:44)
    at readCachedConfig (/usr/lib/node_modules/web-component-tester/node_modules/bower/lib/config.js:30:23)
    at defaultConfig (/usr/lib/node_modules/web-component-tester/node_modules/bower/lib/config.js:19:24)
    at Object.<anonymous> (/usr/lib/node_modules/web-component-tester/node_modules/bower/lib/index.js:40:32)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! web-component-tester@3.3.10 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the web-component-tester@3.3.10 postinstall script.
npm ERR! This is most likely a problem with the web-component-tester package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls web-component-tester
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-62-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "web-component-tester"
npm ERR! cwd /home/tkuchs
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

```sh
$ npm owner ls web-component-tester
nevir <ian@nevir.net>
polymer <admin@polymer-project.org>
azakus <dfreedm2@gmail.com>
```

**Comment by azakus** [comment] 2015-08-24 18:52
This is a duplicate of bower/bower#1607. This file, and a few others, are used by bower when installing. 

I can try to make the `bower install` portion of wct use temporary file locations.

The best scenario would be to not use `sudo` when installing. There's a whole class of issues that go away when you only install as your local user.

**Comment by Zhangyuxia** [comment] 2015-09-01 11:21
@nhatbui Thanks, it works.  ^_^

**Comment by itumoraes** [comment] 2015-09-16 04:54
`sudo chmod g+rw ~/.config/configstore/bower-github.yml` resolved the problem for me...

**Comment by anthonykoerber** [comment] 2015-09-16 22:35
Avoiding `sudo`  has been the best course of action for me. Follow the directions here for great victory: https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npm-s-default-directory-to-another-directory

**Comment by gazal-k** [comment] 2015-09-17 07:42
@anthonykoerber that helped. Thanks :+1:

**Comment by Crysp** [comment] 2015-09-19 21:12
@nhatbui Thanks

**Comment by nick2474** [comment] 2015-10-01 03:58
I got luck doing:
chmod g+rw ~/.config/configstore/bower-github.yml

**Comment by ErikSaunier** [comment] 2015-10-27 13:03
Run `sudo chown -R `whoami` /Users/[username]/.config/configstore` on OSX

**Comment by mmestica** [comment] 2015-11-11 06:57
@nhatbui `chown` worked for me

**Comment by esatemre** [comment] 2015-11-21 10:05
Thanks, @nhatbui worked for me too

**Comment by HaeckDesign** [comment] 2015-11-23 03:24
Solid call - Thank you infinitely @Nhatbui.

**Comment by abell123456** [comment] 2015-11-30 08:43
`sudo chown -R [username] ~/.cache/bower/`
`sudo chown -R [username] ~/.config/configstore/`
@nhatbui 3Q so much!

**Comment by sulhome** [comment] 2015-12-02 13:17
this `sudo chown -R [username] ~/.config/configstore/` worked for me on **Ubuntu 14.04.3 LTS**

**Closed** 2015-12-11 19:42 UTC

**Comment by kasperschnack** [comment] 2015-12-29 10:11
Thanks @nhatbui - worked for me!

**Comment by diegolamanno** [comment] 2016-01-06 15:36
Thanks, @ErikSaunier - Worked for me!

**Comment by souzace** [comment] 2016-01-08 13:58
@kel-dev thanks, work for me.

**Comment by Mirrorhanyu** [comment] 2016-01-26 10:28
@sulhome Thanks, it works!

**Comment by herrowna** [comment] 2016-01-28 02:49
`sudo chown -R [username] ~/.config/configstore/` worked for me as well.

**Comment by thekavish** [comment] 2016-02-22 05:16
Thanks @nhatbui, got my fix.

**Comment by khanstark** [comment] 2016-03-27 15:26
I was annoyed so gave it all permissions:
`sudo chmod 777 ~/.config/configstore/bower-github.yml`
Thus it worked!!

**Comment by lzszone** [comment] 2016-05-09 19:09
thanks @nhatbui
