### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by uqclien** [Polymer/web-component-tester#333] opened 2016-06-27 02:12 UTC
I am getting this error in 4.3.1, worked fine in 4.2.2

Starting local WCT tests

/home/rof/.nvm/v0.10.46/lib/node_modules/web-component-tester/runner/cli.js:11
const chalk = require('chalk');
^^^^^
SyntaxError: Use of const in strict mode.
at Module._compile (module.js:439:25)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/home/rof/.nvm/v0.10.46/lib/node_modules/web-component-tester/runner.js:11:11)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)

**Comment by justinfagnani** [comment] 2016-06-27 16:50
This is a duplicate of #332

**Closed by justinfagnani** 2016-06-27 16:50 UTC
