### ISSUE TITLE
More info if Selenium fails to start

### ISSUE THREAD

**Issue by jreichenberg** [Polymer/web-component-tester#142] opened 2015-03-12 23:44 UTC
in check-started.js there's a loop that looks for the Selenium server by hitting it with a request.  The code currently eats and error and status code from the request, and just logs a blanket 'Unable to connect to selenium' message when the retry limit is reached.  It would be much nicer to log the last request error and status code.  In my case, it fails with UNABLE_TO_VERIFY_LEAF_SIGNATURE (found after I manually added console logging).

Thanks!

**Comment by nevir** [comment] 2015-03-18 00:02
Dupe of #143

**Closed by nevir** 2015-03-18 00:02 UTC
